Repository SiyuanChen-main/Group_F_Student-Management-System, pull requests merged in 2020-12, with the labels that each got.

#30 Adding 'Save to File' functions - START
  include/db.h
  src/db.c
Labels: enhancement

#36 Debug after last merge
  Makefile
  bin/stumgr
  config/configuration_file.txt
  include/db.h
  src/db.c
  src/main.c
  src/ui.c
  src/user.c
Labels: debug

#37 add doxygen to ui.c
  src/ui.c
Labels: documentation

#38 Doxygen comments: user, util parts
  include/user.h
  include/utils.h
  src/user.c
  src/utils.c
Labels: documentation

#39 Code and logic clean up
  include/user.h
  include/utils.h
  src/db.c
  src/ui.c
  src/user.c
  src/utils.c
Labels: CleanUp

#41 Fix adaptability issues: LF and CR+LF
  src/db.c
Labels: debug

#42 Code cleanup and minor fix
  include/platform.h
  src/db.c
  src/user.c
  src/utils.c
Labels: CleanUp

#43 Addition of Doxygen comments according to convention
  include/db.h
  src/db.c
Labels: documentation

#47 add doxygen to the ui.h
  include/ui.h
Labels: documentation

#46 Add images for Wiki documentation
  img/Chart1.png
  img/StudentUserAdd.png
  img/StudentUserDelete.png
  img/StudentUserModify.png
  img/StudentUserSearch.png
  img/adminFunctions.JPG
  img/enterUserPass.JPG
  img/welcomeScreen.JPG
Labels: documentation

#48 Replace tab to 4 spaces
  include/db.h
  include/stu.h
  src/db.c
  src/main.c
  src/stu.c
  src/ui.c
  src/user.c
  src/utils.c
Labels: CleanUp

#49 Update Readme.md
  Readme.md
Labels: documentation
